# -*- coding: utf-8 -*-
"""Task 2: End-to-End ML Pipeline with Scikit-learn Pipeline API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Etj8f9OHy8Zy8h55vHf9Xda0mlEEJCTM

#Telco Churn Dataset

**Objective:** Build a reusable and production-ready ML pipeline for predicting customer churn.

**[Download Dataset](https://drive.google.com/file/d/1795LiN5kTL7n-5yblN5zcYs1Ax_1D_hX/view?usp=sharing)**

**Import Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve)
import joblib

"""**Load and Explore the Dataset**"""

df = pd.read_csv('/content/drive/MyDrive/Telco-Customer-Churn.csv')
display(df.head())
display(df.tail())

df.describe()
df.info()
df.shape

df.isnull().sum()

"""**Exploratory Data Analysis (EDA)**"""

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df['Churn'].value_counts().plot(kind='bar', ax=axes[0], color=['steelblue', 'salmon'])
axes[0].set_title('Churn Distribution')
axes[0].set_xlabel('Churn')
axes[0].set_ylabel('Count')
axes[0].tick_params(rotation=0)

df.boxplot(column='tenure', by='Churn', ax=axes[1])
axes[1].set_title('Tenure by Churn')
axes[1].set_xlabel('Churn')
axes[1].set_ylabel('Tenure (months)')
plt.suptitle('')
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
df.boxplot(column='MonthlyCharges', by='Churn', ax=axes[0])
axes[0].set_title('Monthly Charges by Churn')
axes[0].set_xlabel('Churn')

ct = df.groupby(['Contract', 'Churn']).size().unstack()
ct.plot(kind='bar', ax=axes[1], color=['steelblue', 'salmon'])
axes[1].set_title('Contract Type vs Churn')
axes[1].tick_params(rotation=15)
plt.suptitle('')
plt.tight_layout()
plt.show()

"""**Data Preprocessing**"""

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print("NaNs in TotalCharges after conversion:", df['TotalCharges'].isnull().sum())

df.drop(columns=["customerID"], inplace=True)
df['Churn'] = (df['Churn'] == 'Yes').astype(int)

print("\nChurn value counts after encoding:")
print(df['Churn'].value_counts())

X = df.drop(columns=['Churn'])
y = df['Churn']

numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()

print("Numerical columns:", numerical_cols)
print("\nCategorical columns:", categorical_cols)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")
print(f"\nChurn rate Train: {y_train.mean():.2%} | Test: {y_test.mean():.2%}")

"""**Build Scikit-learn Pipeline**"""

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

preprocessor = ColumnTransformer(transformers=[
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)])

print("Preprocessor built successfully!")
print(preprocessor)

"""**Train Models**

**Model 1: Logistic Regression**
"""

lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, random_state=42))])

lr_pipeline.fit(X_train, y_train)

y_pred_lr = lr_pipeline.predict(X_test)
y_prob_lr = lr_pipeline.predict_proba(X_test)[:, 1]

print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_lr):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr, target_names=['No Churn', 'Churn']))

"""**Model 2: Random Forest**"""

rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1))])

rf_pipeline.fit(X_train, y_train)

y_pred_rf = rf_pipeline.predict(X_test)
y_prob_rf = rf_pipeline.predict_proba(X_test)[:, 1]

print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_rf):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf, target_names=['No Churn', 'Churn']))

"""**Hyperparameter Tuning with GridSearchCV**"""

param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [None, 10, 20],
    'classifier__min_samples_split': [2, 5]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=cv,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("\nBest Parameters:", grid_search.best_params_)
print(f"Best CV ROC-AUC: {grid_search.best_score_:.4f}")

"""**Evaluate the Best Model**"""

best_pipeline = grid_search.best_estimator_
y_pred_best = best_pipeline.predict(X_test)
y_prob_best = best_pipeline.predict_proba(X_test)[:, 1]

print("=== Best Model (Tuned Random Forest) ===")
print(f"Accuracy: {accuracy_score(y_test, y_pred_best):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test, y_prob_best):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_best, target_names=['No Churn', 'Churn']))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

cm = confusion_matrix(y_test, y_pred_best)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['No Churn', 'Churn'], yticklabels=['No Churn', 'Churn'])
axes[0].set_title('Confusion Matrix - Best Model')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('Actual')

for y_prob, label in [(y_prob_lr, 'Logistic Regression'),
                      (y_prob_rf, 'Random Forest'),
                      (y_prob_best, 'Tuned RF (Best)')]:
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc = roc_auc_score(y_test, y_prob)
    axes[1].plot(fpr, tpr, label=f'{label} (AUC = {auc:.3f})')

axes[1].plot([0, 1], [0, 1], 'k--', label='Random')
axes[1].set_title('ROC Curves - Model Comparison')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend()

plt.tight_layout()
plt.show()

"""**Feature Importance**"""

ohe_features = best_pipeline.named_steps['preprocessor']\
                            .named_transformers_['cat']\
                            .named_steps['onehot']\
                            .get_feature_names_out(categorical_cols).tolist()

all_features = numerical_cols + ohe_features

importances = best_pipeline.named_steps['classifier'].feature_importances_

feat_df = pd.DataFrame({'Feature': all_features, 'Importance': importances})
feat_df = feat_df.sort_values('Importance', ascending=False).head(15)

plt.figure(figsize=(10, 6))
sns.barplot(data=feat_df, x='Importance', y='Feature', palette='viridis')
plt.title('Top 15 Feature Importances (Tuned Random Forest)')
plt.tight_layout()
plt.show()

"""**Export Model Pipeline**"""

model_path = 'churn_pipeline.pkl'
joblib.dump(best_pipeline, model_path)
print(f"Pipeline saved to: {model_path}")

loaded_pipeline = joblib.load(model_path)
sample = X_test.iloc[:5]
preds = loaded_pipeline.predict(sample)
probs = loaded_pipeline.predict_proba(sample)[:, 1]

print("\nSample predictions from reloaded model:")
result_df = sample[['tenure', 'MonthlyCharges', 'Contract']].copy()
result_df['Predicted_Churn'] = preds
result_df['Churn_Probability'] = probs.round(3)
display(result_df)

print("\nPipeline export and reload verified successfully!")