# -*- coding: utf-8 -*-
"""Task 1: News Topic Classifier Using BERT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fX-JK700yqO8m2xERS5BF4zZ9CIODKdJ
"""

!pip install -U "pandas<3.0" "requests==2.32.4"
!pip install torch transformers datasets evaluate scikit-learn gradio accelerate

import pandas as pd
from datasets import Dataset, DatasetDict

print("Loading AG News dataset via alternate source...")

train_url = "https://raw.githubusercontent.com/mhjabreel/CharCnn_Keras/master/data/ag_news_csv/train.csv"
test_url = "https://raw.githubusercontent.com/mhjabreel/CharCnn_Keras/master/data/ag_news_csv/test.csv"

train_df = pd.read_csv(train_url, header=None, names=["label", "title", "description"])
test_df = pd.read_csv(test_url, header=None, names=["label", "title", "description"])

# Title aur Description ko mila kar "text" column banana
train_df["text"] = train_df["title"] + " " + train_df["description"]
test_df["text"] = test_df["title"] + " " + test_df["description"]

# Labels ko 0, 1, 2, 3 mein convert karna (BERT ke liye)
train_df["label"] = train_df["label"] - 1
test_df["label"] = test_df["label"] - 1

dataset = DatasetDict({
    "train": Dataset.from_pandas(train_df[["text", "label"]]),
    "test": Dataset.from_pandas(test_df[["text", "label"]])
})

print("Dataset successfully loaded!")
print(dataset)

from transformers import AutoTokenizer

model_ckpt = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)

print("Tokenizing dataset...")
tokenized_datasets = dataset.map(tokenize_function, batched=True)
print("Tokenization complete!")

from transformers import AutoModelForSequenceClassification

num_labels = 4
print("Loading BERT model...")
model = AutoModelForSequenceClassification.from_pretrained(model_ckpt, num_labels=num_labels)
print("Model loaded successfully!")

import numpy as np
import evaluate
from transformers import TrainingArguments

# Metrics load karna
accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_metric.compute(predictions=predictions, references=labels)["accuracy"]
    f1 = f1_metric.compute(predictions=predictions, references=labels, average="macro")["f1"]
    return {"accuracy": acc, "f1": f1}

# Humne saari problematic strategies hata di hain taake error ka chance hi khatam ho jaye
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=500,
    report_to="none"
)
print("Cell 5 successfully run without any error!")

from transformers import Trainer

# Dataset ko chota select kar rahe hain taake training bina hang huay jaldi ho jaye
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(2000))

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
)

print("Starting BERT training... Please wait 1-2 minutes.")
trainer.train()
print("Training finished successfully! Now move to Cell 7.")

print("Saving fine-tuned model...")
model.save_pretrained("./fine_tuned_bert_ag_news")
tokenizer.save_pretrained("./fine_tuned_bert_ag_news")
print("Model saved successfully in folder: ./fine_tuned_bert_ag_news")

import gradio as gr
import torch

# AG News ki 4 classes ke naam
id2label = {0: "World", 1: "Sports", 2: "Business", 3: "Sci/Tech"}

def predict_news_category(text):
    if not text.strip(): return "Please enter some text."

    # Text ko model ke mutabiq tokenize karna
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=128)

    with torch.no_grad():
        outputs = model(**inputs)
        # Probabilities nikalna
        probabilities = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]

    # Har class ki percentage return karna
    return {id2label[i]: float(probabilities[i]) for i in range(len(id2label))}

# Gradio interface setup
interface = gr.Interface(
    fn=predict_news_category,
    inputs=gr.Textbox(lines=3, placeholder="Enter a news headline here... (e.g., Ronaldo scores a goal)", label="News Headline"),
    outputs=gr.Label(num_top_classes=4, label="Predicted Topic"),
    title="📰 AG News Topic Classifier (BERT)"
)

# App ko live share karna
interface.launch(share=True)